In [13]:
import pandas as pd
df = pd.read_csv("top40.csv")
df

df2 = pd.DataFrame()
df2["Tool"] = df["Tool"]
df2["2015"] = df["2015"]
df2["2019"] = df["2019"]
df2["Overall"] = df["2015"] + df["2016"] + df["2017"] + df["2018"] + df["2019"]
df2

          Tool  2015  2019  Overall
0       Python     9    35      125
1   JavaScript     8    15       59
2      Twitter    10    12       82
3       GitHub     2    10       40
4        Gephi    11     9       60
5     GeoNames     2     8       18
6  Transkribus     0     8       12
7        Excel     5     7       30
8        MySQL     0     7       27